function moveslider
h.fig=figure('units','centimeters','position',[1,1,38.5,20],...
    'toolbar','none','menu','none','name','Signal inspection');

% h.main=uipanel('parent',h.fig,'units','normalized','position',[0 0 1 1],...
%     'visible','on','backgroundcolor','white');

h.move= uipanel('parent',h.fig,...
    'units','centimeters',...
    'position', [0 0 1 1]);

h.check = uicontrol('style','checkbox','units','centimeters',...
    'position',[10,15.5,3.5,1],'string','Place/use cursor',...
    'parent',h.move,'Callback',@placeCursor); 

h.slider=uicontrol('parent',h.fig,'units','centimeters',...
    'position',[0.99 0 0.02 1],...
    'style', 'slider',...
    'value', 1,...
    'callback', {@SliderCallback, h});

guidata(h.fig,h)

function SliderCallback(~,~,~)
    val = get(hObject,'Value');
    set(h.move, 'Position', [0 -val 3 1.95]);
end

end